Messages.msg || Notes: Use . to seperate each letter, and _ for spaces. Use # for periods. ^ for next line, and & for next page. ` for a continue.
//INITIALIZER - DONT TOUCH!\\
A.B.C.D.E.F.G.H.I.J.K.L.M.N.O.P.Q.R.S.T.U.V.W.X.Y.Z.a.b.c.d.e.f.g.h.i.j.k.l.m.n.o.p.q.r.s.t.u.v.w.x.y.z.1.2.3.4.5.6.7.8.9.0.`.~.!.@.#.$.%.^.&.*.(.).-.=._.+.[.].\.{.}.|.;.'.:.".,./.<.>.?
//A000.1\\
U.N.D.E.F.I.N.E.D
//A000.2\\
U.N.D.E.F.I.N.E.D
