Messages.msg || Notes: Use . to seperate each letter, and _ for spaces. Use # for periods. ^ for next line, and & for next page. ` for a continue.
//INITIALIZER - DONT TOUCH!\\
A.B.C.D.E.F.G.H.I.J.K.L.M.N.O.P.Q.R.S.T.U.V.W.X.Y.Z.a.b.c.d.e.f.g.h.i.j.k.l.m.n.o.p.q.r.s.t.u.v.w.x.y.z.1.2.3.4.5.6.7.8.9.0.`.~.!.@.#.$.%.^.&.*.(.).-.=._.+.[.].\.{.}.|.;.'.:.".,./.<.>.?
//A000.1\\
W.h.e.r.e._.a.m._.I.?
//A000.2\\
W.h.y._.a.r.e._.y.o.u._.a.s.k.i.n.g.^.m.e._.i.f._.I._.d.o.n.'.t._.k.n.o.w.?.^.`.&.I.t.'.s._.b.e.c.a.u.s.e._.y.o.u.^.a.r.e._.a.n._.i.d.i.o.t.#.`.&.A.m._.N.o.t.#
